import { User, Project, Task, Department } from './types';

export const departments: Department[] = [
  { id: 'dept-1', name: 'Engineering' },
  { id: 'dept-2', name: 'Design' },
  { id: 'dept-3', name: 'Product' },
  { id: 'dept-4', name: 'Marketing' },
  { id: 'dept-5', name: 'Sales' },
];

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Alex Chen',
    email: 'alex@company.com',
    role: 'admin',
    department: 'Engineering',
    dateOfBirth: '1990-03-15',
    address: '123 Tech Street, San Francisco, CA',
    photoUrl: '',
    experience: 10,
    currentWorkload: 45,
  },
  {
    id: 'user-2',
    name: 'Sarah Mitchell',
    email: 'sarah@company.com',
    role: 'manager',
    department: 'Engineering',
    dateOfBirth: '1992-07-22',
    address: '456 Innovation Ave, San Francisco, CA',
    photoUrl: '',
    experience: 7,
    currentWorkload: 65,
  },
  {
    id: 'user-3',
    name: 'James Wilson',
    email: 'james@company.com',
    role: 'manager',
    department: 'Design',
    dateOfBirth: '1994-11-08',
    address: '789 Creative Blvd, San Francisco, CA',
    photoUrl: '',
    experience: 5,
    currentWorkload: 55,
  },
  {
    id: 'user-4',
    name: 'Emily Rodriguez',
    email: 'emily@company.com',
    role: 'member',
    department: 'Engineering',
    dateOfBirth: '1996-05-12',
    address: '321 Developer Lane, San Francisco, CA',
    photoUrl: '',
    experience: 3,
    currentWorkload: 70,
  },
  {
    id: 'user-5',
    name: 'David Kumar',
    email: 'david@company.com',
    role: 'member',
    department: 'Engineering',
    dateOfBirth: '1997-09-30',
    address: '654 Code Street, San Francisco, CA',
    photoUrl: '',
    experience: 2,
    currentWorkload: 60,
  },
  {
    id: 'user-6',
    name: 'Lisa Thompson',
    email: 'lisa@company.com',
    role: 'member',
    department: 'Design',
    dateOfBirth: '1995-02-14',
    address: '987 Design Drive, San Francisco, CA',
    photoUrl: '',
    experience: 4,
    currentWorkload: 75,
  },
  {
    id: 'user-7',
    name: 'Michael Anderson',
    email: 'michael@company.com',
    role: 'member',
    department: 'Engineering',
    dateOfBirth: '1998-12-25',
    address: '147 Tech Park, San Francisco, CA',
    photoUrl: '',
    experience: 1,
    currentWorkload: 50,
  },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'AI Integration Platform',
    description: 'Build comprehensive AI integration system for enterprise clients',
    managerId: 'user-2',
    memberIds: ['user-4', 'user-5', 'user-7'],
    status: 'in-progress',
    createdAt: '2024-01-15',
    progress: 65,
  },
  {
    id: 'proj-2',
    name: 'Mobile App Redesign',
    description: 'Complete overhaul of mobile application user interface',
    managerId: 'user-3',
    memberIds: ['user-6'],
    status: 'in-progress',
    createdAt: '2024-02-01',
    progress: 45,
  },
  {
    id: 'proj-3',
    name: 'Backend Optimization',
    description: 'Optimize database queries and API performance',
    managerId: 'user-2',
    memberIds: ['user-4', 'user-7'],
    status: 'planning',
    createdAt: '2024-02-10',
    progress: 20,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    assignedTo: 'user-4',
    title: 'Setup API endpoints',
    description: 'Create REST endpoints for AI service',
    status: 'done',
    priority: 'high',
    createdAt: '2024-01-16',
    dueDate: '2024-02-05',
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    assignedTo: 'user-5',
    title: 'Implement authentication',
    description: 'Add OAuth2 authentication flow',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2024-01-20',
    dueDate: '2024-02-15',
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    assignedTo: 'user-7',
    title: 'Database schema design',
    description: 'Design and implement database schema',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2024-01-22',
    dueDate: '2024-02-20',
  },
  {
    id: 'task-4',
    projectId: 'proj-2',
    assignedTo: 'user-6',
    title: 'Create UI mockups',
    description: 'Design mobile app UI in Figma',
    status: 'in-progress',
    priority: 'medium',
    createdAt: '2024-02-02',
    dueDate: '2024-02-25',
  },
  {
    id: 'task-5',
    projectId: 'proj-2',
    assignedTo: 'user-6',
    title: 'Implement navigation',
    description: 'Build bottom tab navigation',
    status: 'to-do',
    priority: 'medium',
    createdAt: '2024-02-05',
    dueDate: '2024-03-10',
  },
];

// Mock credentials for login
export const validCredentials = [
  { username: 'admin', password: 'admin123', userId: 'user-1' },
  { username: 'sarah', password: 'sarah123', userId: 'user-2' },
  { username: 'james', password: 'james123', userId: 'user-3' },
  { username: 'emily', password: 'emily123', userId: 'user-4' },
  { username: 'david', password: 'david123', userId: 'user-5' },
  { username: 'lisa', password: 'lisa123', userId: 'user-6' },
  { username: 'michael', password: 'michael123', userId: 'user-7' },
];
